### PR TITLE
Use littleproxy-mitm instead of custom MITMManager

### PR DESCRIPTION
**Pull request by aianus**
The custom MITMManager in Betamax at the moment seems very buggy (I could not get it to work except intermittently) and fills up the root of my project with unnecessary keystores, certs, and truststores.

I propose using the [LittleProxy-mitm](https://github.com/ganskef/LittleProxy-mitm) which generates certs on the fly without shelling out to openssl and saving them to disk.

### CODE REVIEW

**Comment by cowboygneox** [comment]
My apologies for the reported buggy nature of the Betamax MITM manager. I don't recall any request for support, and I would've appreciate an opportunity to help.

MITM is not an easy concept to implement within the JVM. Assuming that this manager works, which it looks like it will, you'll have to ensure the certificate authority is included in the Docker image we use to run the tests or else the tests will fail.

I'm always a little hesitant to adding another project dependency, but if you feel strongly that ganskef has solved the problem significantly better than I have, then I will have to consider it.

**Comment by aianus** [comment]
> you'll have to ensure the certificate authority is included in the Docker image we use to run the tests or else the tests will fail.

I'm using the same root key and cert that's already present in betamax so this PR is backwards compatible with the existing Docker images and existing users of Betamax

**Comment by aianus** [comment]
Ah I see now the included tests are failing with SSL errors (I had previously tested directly in my project).

Let me look into the test failures and get back to you.

**Comment by aianus** [comment]
@cowboygneox 

I'm not familiar enough with groovy and the test internals of betamax to fix these tests but I can say that it's now working perfectly in my project with these changes (and with the same backwards-compatible betamax root cert).

To be specific, the problems I was encountering with 2.0.1 were that the fake certificates presented by the proxy did not have a complete chain to the betamax root cert, it was just a single certificate. With these changes, it presents the whole chain.

Maybe you can look into why these tests or failing or why I had been seeing those issues on 2.0.1?

**Comment by cowboygneox** [comment]
I will try to make time to investigate this within the week, maybe the weekend. Did you try pulling the Docker image and running tests through that and seeing if the tests fail reliably on your machine then?

**Comment by cowboygneox** [comment]
This has not been forgotten, I'm just trying to find time to look. Hopefully the holidays free me up a bit.

**Comment by cowboygneox** [comment]
#224 is likely why you're having issues. I'm on it.

**Comment by aianus** [comment]
Unfortunately our team has switched from Play! framework to Ruby on Rails so I am not able to spend any more time working on this. I think it's worth taking a look at the implementation of littleproxy-mitm and at the temporary file portion of this PR in order to avoid polluting the project directory with all those .crt files etc.


In any case, it's up to you.

**Comment by cowboygneox** [comment]
Taking ownership in #226.

**Pull request closed without merging**
