### PR TITLE
Fix the example scala app to be updated with the released version 2.0.1

### PR DESCRIPTION
**Pull request by MarkBorcherding**

### CODE REVIEW

**Comment by cowboygneox** [comment]
Thanks for doing this!

**Comment by MarkBorcherding** [comment]
Is it not going to get merged?

**Comment by cowboygneox** [comment]
@MarkBorcherding Whoops! I should've waited until I had my coffee...Thanks!

**Comment by MarkBorcherding** [comment]
No problem. I also changed the on the website to point to this directory since the example project mentioned is missing.

**Comment by cowboygneox** [comment]
@MarkBorcherding Do you mean the github pages? I don't maintain that. Eventually they'll be migrated over here, but 2.0 is different from 1.0.

**Comment by MarkBorcherding** [comment]
Yea. https://github.com/betamaxteam/betamaxteam.github.com/pull/2

**Pull request merged**
