### PR TITLE
Start ProxyServer once for each test class

### PR DESCRIPTION
**Pull request by strmer15**
When running this from a JUnit test class with both @ClassRule and @Rule, the RecorderRule separates out the concerns of starting the server and starting the recorder.  If running the recorder directly, the previous behavior is maintained; that is, it will automatically start the server.

A new configuration property was introduced to create the proxy on startup - it defaults to true, but is overridden by the JUnit rule startup.  Also, a TapeProvider interface was introduced to allow dynamic loading of tapes from the ProxyServer, so that each time a test method is run with a new Tape, it's retrieved correctly in the proxy routines.

There's also code to allow users to specify a proxyPort of '0' - when this happens, the actual port is looked up and attempted to be bound; if it fails, the process retries until it finds an open port.  The actual port is also sent into the proxyOverrider to set up the JDK proxy properties correctly; it used to always follow the config value, which is incorrect when '0' is used.

Lastly, a bug fix - when the ProxyConfiguration specified a default tape mode, it would be ignored because the @Betamax annotation specified a default already that would override it; I introduced an UNKNOWN tape mode that returns an Optional.absent().

### CODE REVIEW

**Comment by cowboygneox** [comment]
@strmer15 I can't believe I haven't commented on this yet, but I'll try to look at this over the weekend.

**Comment by strmer15** [comment]
@cowboygneox It's all good - I'm just glad you've gotten this project back up on it's feet.  Looks like I need to re-merge with master anyways to resolve some conflicts from your recent changes.

**Comment by cowboygneox** [comment]
@strmer15 This is going to take a bit to review. Perhaps we should arrange a time when we can be online together to discuss?

**Comment by strmer15** [comment]
@cowboygneox Sorry for the wait, trying to fix these unit test failures, they always work locally but fail on travis.

I'm generally online in the afternoon US/Eastern, I can also try to schedule some time on Saturday or Sunday as well.

**Comment by strmer15** [comment]
I can't seem to find time to work on this, plus I'm thinking my whole approach to this isn't working well - I'm going to close and try to rework it sometime.

**Pull request closed without merging**
